### ISSUE TITLE
EPIC: docusaurus docs website

### ISSUE THREAD

**Issue by srdtrk** [srdtrk/cw-ica-controller#45]
## Description

Have a docusaurus website which has the following:

- [ ]  Search bar
- [ ] Overview
- [ ] How it works
- [ ] Demos
- [ ] Integration
- [ ] Deploy to github sites
- [ ] CI job for checking links and deployment
